package com.gaoliwei.aaos.mapper;

import com.gaoliwei.aaos.domain.Class;
import com.gaoliwei.aaos.domain.Class;

import java.util.List;
import java.util.Map;

public interface ClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Apr 04 08:47:57 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Apr 04 08:47:57 CST 2022
     */
    int insert(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Apr 04 08:47:57 CST 2022
     */
    int insertSelective(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Apr 04 08:47:57 CST 2022
     */
    Class selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Apr 04 08:47:57 CST 2022
     */
    int updateByPrimaryKeySelective(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Apr 04 08:47:57 CST 2022
     */
    int updateByPrimaryKey(Class record);


    /**
     * 通过条件去检索所有的班级
     * @return
     */
    List<Class> selectAllClassesByCondition(Map<String, Object> map);


    /**
     * 插入一个班级的具体信息至表格
     * @param teacher
     * @return
     */
    int insertClass(Class teacher);


    /**
     * 通过id查询班级信息
     * @param id
     * @return
     */
    Class selectClassById(String id);


    /**
     * 更新班级的具体的信息
     * @param class01
     * @return
     */
    int updateClass(Class class01);


    /**
     * 根据id数组删除指定的班级信息
     * @param id
     * @return
     */
    int deleteClassByIds(String[] id);


    /**
     * 检索所有的班级信息
     * @return
     */
    List<Class> selectAllClasses();


    /**
     * 通过id检索所有的班级信息
     * @param id
     * @return
     */
    List<Class> selectAllClassByIds(String[] id);
}