package com.gaoliwei.aaos.mapper;

import com.gaoliwei.aaos.domain.Course;
import com.gaoliwei.aaos.domain.Course;

import java.util.List;
import java.util.Map;

public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    int insert(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    int insertSelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    Course selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    int updateByPrimaryKeySelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    int updateByPrimaryKey(Course record);


    /**
     * 通过条件去检索所有的课程表
     * @return
     */
    List<Course> selectAllCoursesByCondition(Map<String, Object> map);


    /**
     * 插入一个课程表的具体信息至表格
     * @param course
     * @return
     */
    int insertCourse(Course course);


    /**
     * 通过id查询课程表信息
     * @param id
     * @return
     */
    Course selectCourseById(String id);


    /**
     * 更新课程表的具体的信息
     * @param course
     * @return
     */
    int updateCourse(Course course);


    /**
     * 根据id数组删除指定的课程表信息
     * @param id
     * @return
     */
    int deleteCourseByIds(String[] id);


    /**
     * 检索所有的课程表信息
     * @return
     */
    List<Course> selectAllCourses();


    /**
     * 通过id检索所有的课程表信息
     * @param id
     * @return
     */
    List<Course> selectAllCourseByIds(String[] id);
}