package com.gaoliwei.aaos.domain;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.subject
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacher
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    private String teacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.tbl_class
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    private String tblClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.start_day
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    private String startDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.start_time
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.end_time
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.remarks
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.subject
     *
     * @return the value of course.subject
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.subject
     *
     * @param subject the value for course.subject
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacher
     *
     * @return the value of course.teacher
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacher
     *
     * @param teacher the value for course.teacher
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.tbl_class
     *
     * @return the value of course.tbl_class
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public String getTblClass() {
        return tblClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.tbl_class
     *
     * @param tblClass the value for course.tbl_class
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public void setTblClass(String tblClass) {
        this.tblClass = tblClass == null ? null : tblClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.start_day
     *
     * @return the value of course.start_day
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public String getStartDay() {
        return startDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.start_day
     *
     * @param startDay the value for course.start_day
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public void setStartDay(String startDay) {
        this.startDay = startDay == null ? null : startDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.start_time
     *
     * @return the value of course.start_time
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.start_time
     *
     * @param startTime the value for course.start_time
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.end_time
     *
     * @return the value of course.end_time
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.end_time
     *
     * @param endTime the value for course.end_time
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.remarks
     *
     * @return the value of course.remarks
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.remarks
     *
     * @param remarks the value for course.remarks
     *
     * @mbggenerated Mon Apr 04 16:10:57 CST 2022
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}