package com.gaoliwei.aaos.domain;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_no
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    private String studentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.age
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.belong_class
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    private String belongClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.face_num
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    private Integer faceNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_no
     *
     * @return the value of student.student_no
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_no
     *
     * @param studentNo the value for student.student_no
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.password
     *
     * @return the value of student.password
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.password
     *
     * @param password the value for student.password
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.age
     *
     * @return the value of student.age
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.age
     *
     * @param age the value for student.age
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.belong_class
     *
     * @return the value of student.belong_class
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public String getBelongClass() {
        return belongClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.belong_class
     *
     * @param belongClass the value for student.belong_class
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public void setBelongClass(String belongClass) {
        this.belongClass = belongClass == null ? null : belongClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.face_num
     *
     * @return the value of student.face_num
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public Integer getFaceNum() {
        return faceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.face_num
     *
     * @param faceNum the value for student.face_num
     *
     * @mbggenerated Mon Apr 04 11:12:55 CST 2022
     */
    public void setFaceNum(Integer faceNum) {
        this.faceNum = faceNum;
    }
}