package com.gaoliwei.aaos.domain;

public class ViolateType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column violate_type.id
     *
     * @mbggenerated Tue Apr 12 10:49:50 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column violate_type.name
     *
     * @mbggenerated Tue Apr 12 10:49:50 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column violate_type.grade
     *
     * @mbggenerated Tue Apr 12 10:49:50 CST 2022
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column violate_type.info
     *
     * @mbggenerated Tue Apr 12 10:49:50 CST 2022
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column violate_type.create_time
     *
     * @mbggenerated Tue Apr 12 10:49:50 CST 2022
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column violate_type.id
     *
     * @return the value of violate_type.id
     *
     * @mbggenerated Tue Apr 12 10:49:50 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column violate_type.id
     *
     * @param id the value for violate_type.id
     *
     * @mbggenerated Tue Apr 12 10:49:50 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column violate_type.name
     *
     * @return the value of violate_type.name
     *
     * @mbggenerated Tue Apr 12 10:49:50 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column violate_type.name
     *
     * @param name the value for violate_type.name
     *
     * @mbggenerated Tue Apr 12 10:49:50 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column violate_type.grade
     *
     * @return the value of violate_type.grade
     *
     * @mbggenerated Tue Apr 12 10:49:50 CST 2022
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column violate_type.grade
     *
     * @param grade the value for violate_type.grade
     *
     * @mbggenerated Tue Apr 12 10:49:50 CST 2022
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column violate_type.info
     *
     * @return the value of violate_type.info
     *
     * @mbggenerated Tue Apr 12 10:49:50 CST 2022
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column violate_type.info
     *
     * @param info the value for violate_type.info
     *
     * @mbggenerated Tue Apr 12 10:49:50 CST 2022
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column violate_type.create_time
     *
     * @return the value of violate_type.create_time
     *
     * @mbggenerated Tue Apr 12 10:49:50 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column violate_type.create_time
     *
     * @param createTime the value for violate_type.create_time
     *
     * @mbggenerated Tue Apr 12 10:49:50 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}